### ISSUE TITLE
can i use this great library with class component?

### ISSUE THREAD

**Issue by salmanitb** [retyui/react-native-confirmation-code-field#122] opened 2020-04-28 08:40 UTC
can i use this library for class component??

**Comment by retyui** [comment] 2020-04-28 09:05
@salmanitb Yes! You need to create a wrapper


```js
// Form.js
import MyCodeField from './MyCodeField';

class Form {
  state = {value: ''}

  setValue = (newValue) => this.setState({value: newValue});

  render(){
    return <MyCodeField value={value} setValue={this.setValue}  />
  }
}

// --------------------------------------------------------------------------------------
// MyCodeField.js
import React from 'react';
import { StyleSheet, Text } from 'react-native';

import {
  CodeField,
  Cursor,
  useBlurOnFulfill,
  useClearByFocusCell,
} from 'react-native-confirmation-code-field';

const styles = StyleSheet.create({
  root: { flex: 1, padding: 20 },
  title: { textAlign: 'center', fontSize: 30 },
  codeFiledRoot: { marginTop: 20 },
  cell: {
    width: 40,
    height: 40,
    lineHeight: 38,
    fontSize: 24,
    borderWidth: 2,
    borderColor: '#00000030',
    textAlign: 'center',
  },
  focusCell: {
    borderColor: '#000',
  },
});

const CELL_COUNT = 6;

const MyCodeField = ({ value, setValue }) => {
  const ref = useBlurOnFulfill({ value, cellCount: CELL_COUNT });
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value,
    setValue,
  });

  return (
    <CodeField
      ref={ref}
      {...props}
      value={value}
      onChangeText={setValue}
      cellCount={CELL_COUNT}
      rootStyle={styles.codeFiledRoot}
      keyboardType="number-pad"
      renderCell={({ index, symbol, isFocused }) => (
        <Text
          key={index}
          style={[styles.cell, isFocused && styles.focusCell]}
          onLayout={getCellOnLayoutHandler(index)}
        >
          {symbol || (isFocused ? <Cursor /> : null)}
        </Text>
      )}
    />
  );
};

export default MyCodeField;
```

**Comment by salmanitb** [comment] 2020-04-28 09:07
ty so much...

**Comment by retyui** [comment] 2020-04-28 09:16
@salmanitb Can I close this issue?

**Comment by salmanitb** [comment] 2020-04-28 09:23
@retyui ok.. if i have problem can i asking to u?

**Comment by retyui** [comment] 2020-04-28 09:25
@salmanitb Sure

**Comment by kristoff2016** [comment] 2020-09-25 04:07
about in react hook?

**Comment by retyui** [comment] 2020-09-25 07:06
@kristoff2016 excuse me,
 what?

**Comment by kristoff2016** [comment] 2020-09-25 07:30
I tried to get value from the component but it does not work

`// Form.js
import MyCodeField from './MyCodeField';

const Form = () =>  {
  const [value, setValue] = useState('');

  render(){
    return <MyCodeField value={value} setValue={this.setValue}  />
  }
}

// --------------------------------------------------------------------------------------
// MyCodeField.js
import React from 'react';
import { StyleSheet, Text } from 'react-native';

import {
  CodeField,
  Cursor,
  useBlurOnFulfill,
  useClearByFocusCell,
} from 'react-native-confirmation-code-field';

const styles = StyleSheet.create({
  root: { flex: 1, padding: 20 },
  title: { textAlign: 'center', fontSize: 30 },
  codeFiledRoot: { marginTop: 20 },
  cell: {
    width: 40,
    height: 40,
    lineHeight: 38,
    fontSize: 24,
    borderWidth: 2,
    borderColor: '#00000030',
    textAlign: 'center',
  },
  focusCell: {
    borderColor: '#000',
  },
});

const CELL_COUNT = 6;

const MyCodeField = ({ value, setValue }) => {
  const ref = useBlurOnFulfill({ value, cellCount: CELL_COUNT });
  const [props, getCellOnLayoutHandler] = useClearByFocusCell({
    value,
    setValue,
  });

  return (
    <CodeField
      ref={ref}
      {...props}
      value={value}
      onChangeText={setValue}
      cellCount={CELL_COUNT}
      rootStyle={styles.codeFiledRoot}
      keyboardType="number-pad"
      renderCell={({ index, symbol, isFocused }) => (
        <Text
          key={index}
          style={[styles.cell, isFocused && styles.focusCell]}
          onLayout={getCellOnLayoutHandler(index)}
        >
          {symbol || (isFocused ? <Cursor /> : null)}
        </Text>
      )}
    />
  );
};

export default MyCodeField;`

**Comment by retyui** [comment] 2020-09-25 09:34
You used an invalid code (mixed style class or function)
```diff
const Form = () =>  {
  const [value, setValue] = useState('');


-  render(){ 
    return <MyCodeField value={value} setValue={this.setValue}  />
-  }
}
```

**Comment by kristoff2016** [comment] 2020-09-25 09:50
Hello @retyui thanks for your reply. I got an error from `useClearByFocusCell ` said that `setValue` is not function from `Form.js` when it is trying to get value and sending back to component do you have any example? really appreciated that

**Comment by retyui** [comment] 2020-09-25 11:05
@kristoff2016 I recommend you to use a debugger to find the cause of the issue 

console.log({value, setValue}) // 
useClearByFocusCell(...)

**Closed by retyui** 2020-09-25 11:05 UTC
