### ISSUE TITLE
canPasteCode is not working properly ? or did I done a mistake ?

### ISSUE THREAD

**Issue by gangadhartinmen** [retyui/react-native-confirmation-code-field#22] opened 2018-11-23 01:54 UTC
I had implemented this component in my project with canPasteCode={true}.
the copied 4 letter word (for Eg: 1234) is getting copied in the first of the four boxes.

Could you please help me?

**Comment by gangadhartinmen** [comment] 2018-11-23 03:34
When I pasted 4 digit number, It is getting pasted in first of the four boxes and throwing the error as "Invalid attempt to spread non-iterable instance"

**Comment by retyui** [comment] 2018-11-24 07:56
Can you create a simple demo to reproduce this issue?

**Comment by retyui** [comment] 2018-11-25 13:34
It works for me 

![](https://media.giphy.com/media/wJPw2dEbSFfSilBkRq/giphy.gif)

**Comment by gangadhartinmen** [comment] 2018-11-26 07:15
Thank you so much for your response.

import ConfirmationCodeInput from 'react-native-confirmation-code-field';

inputStyle = (index, isActive, hasValue) => {
	if (hasValue) {
		return styles.inputNotEmpty;
	}
	return null;
};
inputProps = () => ({
	keyboardType: 'numeric',
	style: styles.input,
});

onFinishCheckingCode = code => {
	if (code === '1234') {
		return Alert.alert('Confirmation Code', 'Successful!', [{ text: 'OK' }], {
			cancelable: false,
		});
	}
	Alert.alert('Confirmation Code', 'Code not match!', [{ text: 'OK' }], {
		cancelable: false,
	});
	this.codeInputRef.current.clear();
};

<ConfirmationCodeInput
         onFulfill={this.onFinishCheckingCode}
	canPasteCode={true}
	autoFocus={true}
	codeLength={4}

	ref={this.codeInputRef}
	inputPosition="center"
	variant="border-b"
 	inputProps={this.inputProps}
	inputStyle={this.inputStyle}
/>

const styles = StyleSheet.create({
	input: {
		height: 60,
		width: 60,
		borderRadius: 3,
		borderWidth: 1,
		borderColor: '#000',
		color: '#fff',
		backgroundColor: '#d33b36',
		fontSize: 30,
	fontWeight: '700',
	},
	inputNotEmpty: {
		backgroundColor: '#d33b36',
	},
});

Please check the above code,
![error_ui](https://user-images.githubusercontent.com/28722992/48998315-204c2c80-f179-11e8-8550-c02a55d691c5.jpg)
![error_onpaste](https://user-images.githubusercontent.com/28722992/48998331-29d59480-f179-11e8-9d21-ff51bba26bf0.jpg)

**Comment by retyui** [comment] 2018-11-26 07:19
@gangadhartinmen What version RN do you use?

**Comment by retyui** [comment] 2018-11-26 07:42
So I tested on my Samsung s9, and it still works 
Here demo repo: https://github.com/retyui/demo-confirmation-code-field-issue-22-

![](https://media.giphy.com/media/238iPJ9wBl54JY9XjZ/giphy.gif)

**Comment by retyui** [comment] 2018-11-26 07:44
It would be better to start debugging the problem.

https://facebook.github.io/react-native/docs/debugging

**Comment by gangadhartinmen** [comment] 2018-11-26 09:13
Thank you.
I will debug and let you know.

**Comment by retyui** [comment] 2018-11-28 07:00
Fixed in https://github.com/retyui/react-native-confirmation-code-field/pull/24

**Closed by retyui** 2018-11-28 07:00 UTC

**Comment by gangadhartinmen** [comment] 2018-11-28 11:21
Thank you so much
